"""
Generated by AI Model - v1.0.0
Timestamp: 2025-10-29T16:08:00Z
Facial Recognition Worker - Main Process
"""

import os
import time
import logging
from datetime import datetime
from typing import Optional, Tuple
import cv2
import numpy as np
import requests
from recognition_adapter import RecognitionAdapter
from config import settings

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)


class RecognitionWorker:
    """
    Recognition worker that processes CCTV feeds and performs facial recognition
    """
    
    def __init__(self):
        self.adapter = RecognitionAdapter()
        self.backend_url = settings.BACKEND_URL
        self.camera_streams = settings.CAMERA_STREAMS
        self.processing_interval = settings.PROCESSING_INTERVAL
        
        logger.info(f"Initializing recognition worker with backend: {self.backend_url}")
        
    def process_camera_stream(self, camera_id: str, stream_url: str):
        """Process a single camera stream"""
        logger.info(f"Processing camera stream: {camera_id} from {stream_url}")
        
        # Open video stream
        cap = cv2.VideoCapture(stream_url)
        
        if not cap.isOpened():
            logger.error(f"Failed to open camera stream: {camera_id}")
            return
        
        frame_count = 0
        last_recognition_time = time.time()
        
        try:
            while True:
                ret, frame = cap.read()
                
                if not ret:
                    logger.warning(f"Failed to read frame from {camera_id}, reconnecting...")
                    cap.release()
                    time.sleep(5)
                    cap = cv2.VideoCapture(stream_url)
                    continue
                
                frame_count += 1
                current_time = time.time()
                
                # Process frame every N seconds to avoid overload
                if current_time - last_recognition_time >= self.processing_interval:
                    self.process_frame(frame, camera_id)
                    last_recognition_time = current_time
                
                # Optional: Display frame for debugging
                if settings.DEBUG:
                    cv2.imshow(f'Camera {camera_id}', frame)
                    if cv2.waitKey(1) & 0xFF == ord('q'):
                        break
        
        except KeyboardInterrupt:
            logger.info("Stopping camera processing...")
        finally:
            cap.release()
            cv2.destroyAllWindows()
    
    def process_frame(self, frame: np.ndarray, camera_id: str):
        """Process a single frame for face recognition"""
        try:
            # Detect faces in frame
            face_crops = self.detect_faces(frame)
            
            if not face_crops:
                return
            
            logger.info(f"Detected {len(face_crops)} face(s) in camera {camera_id}")
            
            for face_crop in face_crops:
                # Call recognition adapter
                result = self.adapter.predict(face_crop)
                
                if result['user_id']:
                    # Matched - send to backend
                    self.report_attendance(
                        user_id=result['user_id'],
                        camera_id=camera_id,
                        confidence=result['confidence'],
                        face_image=face_crop
                    )
                else:
                    # Unknown face - report for review
                    self.report_unknown_face(
                        camera_id=camera_id,
                        face_image=face_crop
                    )
        
        except Exception as e:
            logger.error(f"Error processing frame: {e}", exc_info=True)
    
    def detect_faces(self, frame: np.ndarray) -> list:
        """Detect faces in frame and return crops"""
        # Convert to RGB
        rgb_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        
        # Use Haar Cascade for face detection (fast, simple)
        # In production, use MTCNN, RetinaFace, or other advanced detectors
        face_cascade = cv2.CascadeClassifier(
            cv2.data.haarcascades + 'haarcascade_frontalface_default.xml'
        )
        
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        faces = face_cascade.detectMultiScale(gray, 1.3, 5)
        
        face_crops = []
        for (x, y, w, h) in faces:
            # Add padding
            padding = 20
            x_start = max(0, x - padding)
            y_start = max(0, y - padding)
            x_end = min(frame.shape[1], x + w + padding)
            y_end = min(frame.shape[0], y + h + padding)
            
            face_crop = rgb_frame[y_start:y_end, x_start:x_end]
            
            # Filter out very small faces
            if face_crop.shape[0] > 50 and face_crop.shape[1] > 50:
                face_crops.append(face_crop)
        
        return face_crops
    
    def report_attendance(
        self,
        user_id: str,
        camera_id: str,
        confidence: float,
        face_image: np.ndarray
    ):
        """Report recognized face to backend"""
        try:
            # Encode image as JPEG
            _, buffer = cv2.imencode('.jpg', cv2.cvtColor(face_image, cv2.COLOR_RGB2BGR))
            
            # Send to backend
            files = {'image': ('face.jpg', buffer.tobytes(), 'image/jpeg')}
            data = {
                'user_id': user_id,
                'camera_id': camera_id,
                'confidence': confidence,
                'timestamp': datetime.utcnow().isoformat()
            }
            
            response = requests.post(
                f"{self.backend_url}/api/v1/recognition/attendance",
                files=files,
                data=data,
                timeout=10
            )
            
            if response.status_code == 200:
                logger.info(f"Attendance reported for user {user_id}, confidence: {confidence:.2f}")
            else:
                logger.error(f"Failed to report attendance: {response.status_code}")
        
        except Exception as e:
            logger.error(f"Error reporting attendance: {e}", exc_info=True)
    
    def report_unknown_face(self, camera_id: str, face_image: np.ndarray):
        """Report unknown face to backend"""
        try:
            # Encode image
            _, buffer = cv2.imencode('.jpg', cv2.cvtColor(face_image, cv2.COLOR_RGB2BGR))
            
            # Send to backend
            files = {'image': ('unknown.jpg', buffer.tobytes(), 'image/jpeg')}
            data = {
                'camera_id': camera_id,
                'timestamp': datetime.utcnow().isoformat()
            }
            
            response = requests.post(
                f"{self.backend_url}/api/v1/recognition/unknown",
                files=files,
                data=data,
                timeout=10
            )
            
            if response.status_code == 200:
                logger.info(f"Unknown face reported from camera {camera_id}")
        
        except Exception as e:
            logger.error(f"Error reporting unknown face: {e}", exc_info=True)


def main():
    """Main worker entry point"""
    logger.info("Starting facial recognition worker...")
    
    worker = RecognitionWorker()
    
    # In production, process multiple camera streams in parallel
    # For now, process the first camera
    if settings.CAMERA_STREAMS:
        camera_id, stream_url = list(settings.CAMERA_STREAMS.items())[0]
        worker.process_camera_stream(camera_id, stream_url)
    else:
        logger.warning("No camera streams configured")
        logger.info("Running in test mode...")
        
        # Test mode - process static images or video file
        # You can add test video processing here


if __name__ == "__main__":
    main()
